name: Yeogijeogi Dev Build and Deploy

on:
  push:
    branches:
      - feature/cicd
  pull_request:
    branches:
      - develop
#env:
#   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DEV_DOCKER_IMAGE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yeogijeogi:dev
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Set Up ENV
        run: |
           echo "DEV_DOCKER_CONTAINER=${{ secrets.DEV_DOCKER_CONTAINER}}" >> .env
           echo "DEV_DOCKER_IMAGE=${{ secrets.DEV_DOCKER_IMAGE}}" >> .env
           echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
           cat .env

      - name: Stop and Remove Old Dev Containers
        run: |
          sudo docker stop ${{ env.DEV_DOCKER_CONTAINER }} || true && sudo docker rm ${{ env.DEV_DOCKER_CONTAINER }} || true
          sudo docker rmi ${{ env.DEV_DOCKER_IMAGE }}:latest || true

      - name: Run Dev Container
        run: |
            docker pull ${{ env.DOCKER_HUB_USERNAME}}/${{ env.DEV_DOCKER_IMAGE }}
            docker run --env-file ./.env -d -p 8001:8000 --name ${{ env.DEV_DOCKER_CONTAINER }} ${{ env.DOCKER_HUB_USERNAME}}/${{ env.DEV_DOCKER_IMAGE }}
